Opponent ai
grabczak/ramsey-game-backend pull request #1
Opened 2024-11-02 20:36 UTC by Jarugam

2024-11-02 20:42 UTC, grabczak requested changes

2024-11-02 20:42 UTC, grabczak commented on graph_logic.py
> +    return False
`return len(clique) >= k`

2024-11-02 21:17 UTC, grabczak approved these changes

2024-11-02 21:18 UTC, grabczak approved these changes

2024-11-03 21:10 UTC, jarinios approved these changes

2024-11-03 21:13 UTC, jarinios approved these changes

2024-11-04 12:01 UTC, merged